"""Initial migration with user_id

Revision ID: 282cced9174f
Revises: 
Create Date: 2025-09-25 19:33:06.184577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282cced9174f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_log', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
